apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: todolist-namespace
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: social-todo-list-golang-mysql-demo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_NAME
              value: todolist
